# Site settings
title: Collections Description
description: Website for the TDWG Collections Description Interest Group
url: "https://tdwg.github.io"
baseurl: "/cd"

navbar:
  left:
  - text: Charter
    href: charter/
  right:
  - text: GitHub
    href: https://github.com/tdwg/cd

js: >-
  

# Build settings
markdown: kramdown
# theme: tdwg-theme-jekyll
remote_theme: tdwg/tdwg-theme-jekyll
plugins:
  - jekyll-feed
